**Maron Guimarães SQL Activity for week 9**

In [1]:
import sqlite3 #imports sqlite3 tool
import pandas as pd #imports pandas with the pd nickname
conn = sqlite3.connect('my_data.db') #creates a database and connects sqlite3 to it
cursor = conn.cursor() #creates a cursor

In [2]:
pd.read_csv('sales.csv').to_sql('sales',conn,if_exists='replace',index=False)

20

In [3]:
pd.read_sql_query('''
SELECT * FROM sales
''',conn)

    sale_id  sale_date     product     category region  quantity   price
0         1   9/1/2026      Laptop  Electronics   East         2  999.99
1         2   9/1/2026       Mouse  Accessories   East        10   24.99
2         3   9/2/2026     Monitor  Electronics   West         3  199.99
3         4   9/2/2026    Keyboard  Accessories  North         4   49.99
4         5   9/3/2026      Laptop  Electronics   West         1  999.99
5         6   9/3/2026  Headphones  Accessories  South         6   79.99
6         7   9/4/2026       Mouse  Accessories  North         5   24.99
7         8   9/4/2026     Monitor  Electronics   East         2  199.99
8         9   9/5/2026      Laptop  Electronics  South         3  999.99
9        10   9/5/2026    Keyboard  Accessories   West         7   49.99
10       11   9/6/2026  Headphones  Accessories   East         4   79.99
11       12   9/6/2026      Tablet  Electronics  North         2  449.99
12       13   9/7/2026       Mouse  Accessories  South         8   24.99
13       14   9/7/2026      Tablet  Electronics   West         1  449.99
14       15   9/8/2026     Monitor  Electronics  North         2  199.99
15       16   9/8/2026      Laptop  Electronics   East         1  999.99
16       17   9/9/2026    Keyboard  Accessories  South         3   49.99
17       18   9/9/2026  Headphones  Accessories   West         5   79.99
18       19  9/10/2026      Tablet  Electronics   East         3  449.99
19       20  9/10/2026       Mouse  Accessories   West        12   24.99

In [4]:
pd.read_sql_query('''
SELECT sale_date, product, price FROM sales
''',conn)

    sale_date     product   price
0    9/1/2026      Laptop  999.99
1    9/1/2026       Mouse   24.99
2    9/2/2026     Monitor  199.99
3    9/2/2026    Keyboard   49.99
4    9/3/2026      Laptop  999.99
5    9/3/2026  Headphones   79.99
6    9/4/2026       Mouse   24.99
7    9/4/2026     Monitor  199.99
8    9/5/2026      Laptop  999.99
9    9/5/2026    Keyboard   49.99
10   9/6/2026  Headphones   79.99
11   9/6/2026      Tablet  449.99
12   9/7/2026       Mouse   24.99
13   9/7/2026      Tablet  449.99
14   9/8/2026     Monitor  199.99
15   9/8/2026      Laptop  999.99
16   9/9/2026    Keyboard   49.99
17   9/9/2026  Headphones   79.99
18  9/10/2026      Tablet  449.99
19  9/10/2026       Mouse   24.99

In [5]:
pd.read_sql_query('''
SELECT sale_date, product, price FROM sales
''',conn)

    sale_date     product   price
0    9/1/2026      Laptop  999.99
1    9/1/2026       Mouse   24.99
2    9/2/2026     Monitor  199.99
3    9/2/2026    Keyboard   49.99
4    9/3/2026      Laptop  999.99
5    9/3/2026  Headphones   79.99
6    9/4/2026       Mouse   24.99
7    9/4/2026     Monitor  199.99
8    9/5/2026      Laptop  999.99
9    9/5/2026    Keyboard   49.99
10   9/6/2026  Headphones   79.99
11   9/6/2026      Tablet  449.99
12   9/7/2026       Mouse   24.99
13   9/7/2026      Tablet  449.99
14   9/8/2026     Monitor  199.99
15   9/8/2026      Laptop  999.99
16   9/9/2026    Keyboard   49.99
17   9/9/2026  Headphones   79.99
18  9/10/2026      Tablet  449.99
19  9/10/2026       Mouse   24.99

**Task 2**

In [6]:
pd.read_csv('hr_employees.csv').to_sql('employees', conn, if_exists='replace', index=False)

30

In [7]:
pd.read_sql_query('''
SELECT *
FROM employees
''', conn)

,employee_id,name,department,city,salary,years_experience,full_time
0,1001,Emma,HR,Chicago,45000,8,Yes
1,1002,Liam,Marketing,Dallas,55000,17,Yes
2,1003,Olivia,Operations,Atlanta,46000,0,Yes
3,1004,Noah,Marketing,Dallas,106000,19,Yes
4,1005,Ava,Operations,Dallas,111000,13,Yes
5,1006,Ethan,IT,Seattle,77000,0,Yes
6,1007,Sophia,HR,Atlanta,85000,8,Yes
7,1008,Mason,Marketing,Denver,55000,2,No
8,1009,Isabella,Sales,Denver,86000,19,Yes
9,1010,Lucas,Sales,Atlanta,110000,3,No
10,1011,Mia,Sales,Seattle,79000,20,Yes
11,1012,Logan,Operations,Dallas,50000,1,Yes
12,1013,Amelia,Finance,Chicago,71000,3,No
13,1014,James,Finance,Atlanta,123000,11,Yes
14,1015,Harper,Finance,Denver,68000,8,Yes
15,1016,Benjamin,Operations,Dallas,110000,7,Yes
16,1017,Evelyn,IT,Atlanta,76000,20,Yes
17,1018,Henry,HR,Denver,49000,7,Yes
18,1019,Abigail,Finance,Atlanta,76000,2,Yes
19,1020,Jack,Operations,Denver,69000,20,No
20,1021,Ella,IT,Atlanta,60000,8,Yes
21,1022,Owen,Marketing,Seattle,110000,8,No
22,1023,Grace,Operations,Atlanta,88000,7,Yes
23,1024,Daniel,Operations,Atlanta,53000,1,Yes
24,1025,Chloe,Marketing,Dallas,96000,19,Yes
25,1026,Carter,IT,Atlanta,118000,14,Yes
26,1027,Lily,Operations,Chicago,56000,17,Yes
27,1028,Wyatt,HR,Denver,56000,9,No
28,1029,Zoe,Marketing,Atlanta,42000,8,Yes
29,1030,Julian,Operations,Chicago,122000,9,Yes

In [8]:
pd.read_sql_query('''
SELECT name, city, salary
FROM employees
WHERE years_experience > 10 AND city = 'Chicago'
''', conn)

   name     city  salary
0  Lily  Chicago   56000

**Task 3**

In [20]:
# Import necessary libraries if not already imported
import pandas as pd
import sqlite3

# Drop the existing table before inserting new data
# This ensures a clean slate and avoids the "table already exists" error
try:
    conn.execute("DROP TABLE IF EXISTS Listings")
    conn.commit()  # Commit the drop operation
except:
    pass  # If there's any issue dropping, continue anyway

# Now read the CSV and insert into the database
pd.read_csv('realestate_listings.csv').to_sql('Listings', conn, if_exists='replace', index=False)

25

In [10]:
pd.read_sql_query('''
SELECT *
FROM listings
ORDER BY sqft DESC LIMIT 3
''', conn)

,listing_id,neighborhood,property_type,bedrooms,sqft,list_price,days_on_market
0,204,Riverside,Condo,5,3736,979000,71
1,206,Maple Grove,Condo,5,3693,1001000,52
2,209,Maple Grove,House,1,3499,661000,116

**Task 4**

In [21]:
import pandas as pd

# Drop the existing table if it exists
try:
    conn.execute("DROP TABLE IF EXISTS Campaigns")
    conn.commit()  # Commit the drop operation
except:
    pass  # If table doesn't exist or error occurs, continue

# Now read the CSV and create the table
pd.read_csv('marketing_campaigns.csv').to_sql('Campaigns', conn, if_exists='replace', index=False)

40

In [12]:
pd.read_sql_query('''
SELECT *
FROM campaigns
GROUP BY channel
''', conn)

,record_id,campaign,channel,week,impressions,clicks,spend,conversions
0,2,Back to School,Display Ads,6,39814,1186,3737.37,134
1,3,Spring Sale,Email,4,6220,204,2171.77,6
2,5,Spring Sale,Influencer,5,44651,1812,3747.50,55
3,1,Back to School,Search Ads,4,15745,487,2777.99,25
4,15,Summer Launch,Social Media,8,10075,533,1593.74,54

In [13]:
pd.read_sql_query('''
SELECT week, SUM(impressions) AS total_impressions
FROM campaigns
GROUP BY week
''', conn)

   week  total_impressions
0     1             181454
1     2              74972
2     3             193242
3     4             180795
4     5             264615
5     6             229892
6     7             235470
7     8             253354

**Task 5**

In [22]:
import sqlite3

# Drop the table if it exists (handles case-sensitivity issues)
cursor = conn.cursor()
cursor.execute("DROP TABLE IF EXISTS Orders")
conn.commit()

# Now insert the data
pd.read_csv('restaurant_orders.csv').to_sql('Orders', conn, if_exists='replace', index=False)

50

In [15]:
pd.read_sql_query('''
SELECT order_date, ROUND(SUM(order_total), 2) AS total_orders
FROM orders
GROUP BY order_date
HAVING SUM(order_total) > 400
''', conn)

   order_date  total_orders
0  2026-10-02        492.14
1  2026-10-05        850.10
2  2026-10-07        415.94
3  2026-10-12        633.98

**Task 6**

In [16]:
pd.read_csv('clinic_visits.csv').to_sql('visits', conn, if_exists='replace', index=False)

35

In [17]:
pd.read_sql_query('''
SELECT doctor,
       ROUND(AVG(patient_age), 1) AS patient_age,
       MAX(wait_minutes) AS wait_minutes
FROM visits
GROUP BY doctor
''', conn)

      doctor  patient_age  wait_minutes
0  Dr. Adams         47.0            75
1   Dr. Chen         57.6            50
2  Dr. Gomez         33.7            75
3  Dr. Patel         45.4            59
4  Dr. Scott         44.9            63

**Task 7**

In [18]:
pd.read_csv('bank_customers.csv').to_sql('customers', conn, if_exists='replace', index=False)
pd.read_csv('bank_transactions.csv').to_sql('transactions', conn, if_exists='replace', index=False)

45

In [19]:
pd.read_sql_query('''
SELECT c.branch,
SUM(t.amount) AS total_transaction_amount
FROM transactions AS t
JOIN customers AS c ON t.customer_id = c.customer_id
GROUP BY c.branch
''', conn)

      branch  total_transaction_amount
0    Airport                  15177.98
1    Main St                   3581.19
2  Northgate                  19546.49
3   Westside                  13996.30